# Use container-based infrastructure
sudo: false

language: scala

jdk: oraclejdk8

scala:
  - 2.12.8


jobs:
  include:
    - script: "sbt ++$TRAVIS_SCALA_VERSION +test"
    - stage: deploy
      script: "sbt +publish"
      if: repo = Cobliteam/kamon-datadog AND type = push AND (branch = master)


# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete


